name: CI-CD

env:
  DOCKER_IMAGE_NAME: ${{ secrets.REGISTRY_USERNAME }}/marvel-dex-live
  VERSION_PREFIX: v0.0
  CLOUD_RUN_SERVICE_NAME: live-go-jefjrfig

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: "Code checkout"
        uses: actions/checkout@v4.1.5
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: "Docker build e Push da Imagem"
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.VERSION_PREFIX }}.${{ github.run_number }}
            ${{ env.DOCKER_IMAGE_NAME }}:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: "Deploy on Azure App Service"
        uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ env.CLOUD_RUN_SERVICE_NAME }}'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ env.DOCKER_IMAGE_NAME }}:${{ env.VERSION_PREFIX }}.${{ github.run_number }}'
